### ISSUE TITLE
[FEATURE] Allow additional user scripts to be passed for HeadNode and ComputeNode sequence arguments

### ISSUE THREAD

**Issue by gwolski** [aws-samples/aws-eda-slurm-cluster#227]
I'd like to add my own scripts/args for HeadNode and ComputeNode in the OnNodeConfigured/OnNodeStart/OnNodeUpdated  sections.

Right now I have a custom AMI that runs some scripts at boot time, but before parallelcluster has been configured, so it is too early. I really want my script to run after parallelcluster has finished configuring the machine.

I can modify the resultant parallelcluster config file, but then, once again, the aws-eda-slurm config file gets out of date with the actual config file.

**Comment by cartalla** [comment]
I just merged a change with a new ClusterConfig parameter that allows you to set arbitrary ParallelCluster config parameters. You should be able to set your own scripts there and mine will be added after them.

**Comment by cartalla** [comment]
It also add parameters to allow additional security groups and IAM policies for head and compute nodes.

**Comment by cartalla** [comment]
This was resolved in #225 

Use the new ClusterConfig parameter which allows any ParallelCluster configuration parameters.
