### ISSUE TITLE
Error message prints out during SLURM deployment.  

### ISSUE THREAD

**Issue by gwolski** [aws-samples/aws-eda-slurm-cluster#237]
Using latest version as of May 15. SHA code ending in 78a9c.

During the slurm deployment  an error message prints out:

ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists.

This almost looks like a message as if something is looking for a section from an old parallelcluster v2 config file...

The error doesn't seem to cause a problem, but good to remove it if you can - or maybe it is from pcluster itself?

Here is more context as to where the message comes out:

****************************************************
*** Newer version of CDK is available [2.145.0]  ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

....

INFO: 
====== Deploying SLURM ======

ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists.
INFO: Using config: /proj/work/gwolski/aws-eda-slurm-cluster/source/resources/config/tsi2-x86_instance_types.yml
INFO: CIDR                 set from command line: 10.6.0.0/16
INFO: slurm/ClusterName defaulted to tsi2
INFO:2024-06-10 16:20:09,652: /tmp/instance_type_info.json doesn't exist so cannot be read and will be created.
INFO:2024-06-10 16:20:09,652: Getting EC2 pricing info for following regions:
['us-west-2']
INFO:2024-06-10 16:20:09,665: Getting EC2 instance info for us-west-2 (US West (Oregon))

**Comment by gespinal** [comment]
Same issue when trying to enable RES integration.

**Comment by cartalla** [comment]
This is coming from CDK itself and I haven't been able to figure out where it is coming from, but it doesn't cause any issues.
