### ISSUE TITLE
[FEATURE] Restore memory based partitions

### ISSUE THREAD

**Issue by cartalla** [aws-samples/aws-eda-slurm-cluster#261]
**Is your feature request related to a problem? Please describe.**

PR #235 changed the way that AWS ParallelCluster (APC) partitions and compute resources (CRs) were created and named.

Previously, a CR could contain multiple instance types with the same number of cores and amount of memory.
The CR name was (od|sp)-\d+-gb-[\d+]-cores.

CRs with the same amount of memory were grouped into a single APC queue.
The queue name was (od|sp)-\d+-gb.

The new partition naming convention is (od|sp)-<family>-<size>. For example, od-c7i-4xl.

Users prefer to have memory-based partitions that use total memory, not available memory and then constrain the number of required cores.

Form older version, the partitions would look like:

```
PARTITION   AVAIL  TIMELIMIT  NODES  STATE NODELIST
od-4-gb        up   infinite     10  idle~ od-4-gb-dy-od-4gb-1-cores-[1-10]
sp-4-gb        up   infinite     10  idle~ sp-4-gb-dy-sp-4gb-1-cores-[1-10]
od-8-gb        up   infinite     29  idle~ od-8-gb-dy-od-8gb-1-cores-[2-20],od-8-gb-dy-od-8gb-2-cores-[1-10]
```

So a user could submit a job like the following:

```
sbatch -p od-8-gb -c 1 job.sh
```

Note that the current version does support specifying memory and cores.

```
sbatch -c 1 --mem 7700M -p on-demand job.sh
```

## Proposal

Configure the memory and purchase model partitions.

Add constraints for on-demand and spot to give a non-partition-based way of selecting the purchase model.

Also add constraint on nodes with the amount of total memory, not available memory.

**Comment by gwolski** [comment]
Will you be adding slurm constraints (features), so I would use would use 
--constraint=MEM32,SPOT

If I wanted a 32G machine and spot?  Something like that?

Or are you thinking of modifying the pcluster files so the memory is the physical memory of the machine so I can use --mem?

**Comment by cartalla** [comment]
Upon further investigation, ParallelCluster doesn’t allow me to add custom Features to the node configuration. So, I’ll be restoring the partitions that previously existed so you can specify that to get, for example, an od-4-gb machine or a sp-8-gb machine. I also already have spot and on-demand partitions that allow you to specify the purchase option you want to use.

From: Guntram Wolski ***@***.***>
Reply-To: aws-samples/aws-eda-slurm-cluster ***@***.***>
Date: Wednesday, October 16, 2024 at 1:05 PM
To: aws-samples/aws-eda-slurm-cluster ***@***.***>
Cc: "Carter, Allan" ***@***.***>, Assign ***@***.***>
Subject: Re: [aws-samples/aws-eda-slurm-cluster] [FEATURE] Restore memory based partitions (Issue #261)


Will you be adding slurm constraints (features), so I would use would use
--constraint=MEM32,SPOT

If I wanted a 32G machine and spot? Something like that?

Or are you thinking of modifying the pcluster files so the memory is the physical memory of the machine so I can use --mem?

**Comment by cartalla** [comment]
That’s what I wanted to do, but ParallelCluster doesn’t allow me to customize the node’s features.

See this PR for what I’ve done. It will restore the queues that you previously had.

https://github.com/aws-samples/aws-eda-slurm-cluster/pull/263


From: Guntram Wolski ***@***.***>
Reply-To: aws-samples/aws-eda-slurm-cluster ***@***.***>
Date: Wednesday, October 16, 2024 at 1:05 PM
To: aws-samples/aws-eda-slurm-cluster ***@***.***>
Cc: "Carter, Allan" ***@***.***>, Assign ***@***.***>
Subject: Re: [aws-samples/aws-eda-slurm-cluster] [FEATURE] Restore memory based partitions (Issue #261)


Will you be adding slurm constraints (features), so I would use would use
--constraint=MEM32,SPOT

If I wanted a 32G machine and spot? Something like that?

Or are you thinking of modifying the pcluster files so the memory is the physical memory of the machine so I can use --mem?
