### ISSUE TITLE
Document which python program needs to be updated if I need to create the user/group json file a different way

### ISSUE THREAD

**Issue by gwolski** [aws-samples/aws-eda-slurm-cluster#266]
The documentation and the Cloudformation output provide a means to create the json file for the user/groups, but it makes  an assumption that getent passwd will provide the correct information.

For a user of FreeIPA this doesn't work, I need to query the freeipa server. 

I think the proper program to modify is in the source tree at source/resources/parallel-cluster/config/bin/create_users_groups_json.py

Alternatively I could create a passwd file based on the freeIPA data in a separate cron job and feed that into the create_users_groups_json.py if you gave me a hook?

**Comment by cartalla** [comment]
You are correct about the script. 
It gets installed at `/opt/slurm/<ClusterName>/config/bin/create_users_groups_json.py`.

One option is to modify the script for yourself.
Another is to use a custom compute node AMI that either joins the FreeIPA domain or creates corresponding local users and groups.
