### ISSUE TITLE
document command11SubmitterDeconfigure command in instructions.

### ISSUE THREAD

**Issue by gwolski** [aws-samples/aws-eda-slurm-cluster#282]
Looks like your stack output now lists a new useful command:  command11SubmitterDeconfigure.

It is not documented on the wiki: https://aws-samples.github.io/aws-eda-slurm-cluster/deploy-parallel-cluster/

**Comment by cartalla** [comment]
This has been there for a long time. I'll see about adding a page on deleting clusters.

**Comment by gwolski** [comment]
Parallelcluster allows you to replace the AMI if stop things.  I believe your scripts will do the same, but this will cause a problem for the submitter nodes.  They all have the head_node mounted via NFS.  If the head_node is replaced, it will get a different IP address. Unfortunately the head_node is already NFS mounted at the old IP address and the submitter nodes will hang nor will they see the new head_node.

Maybe you need to warn the user before allowing an AMI change to move forward, with reference to this command11SubmitterDeconfigure script (or something appropriate).
