### ISSUE TITLE
[BUG] Permission issue when deploying

### ISSUE THREAD

**Issue by cartalla** [aws-samples/aws-eda-slurm-cluster#31]
I'm having issue when bootstrapping cdk. It successfully bootstrapped when I run this: 

> cdk bootstrap aws://xxxxxxx/us-east-1 -c region=us-east-1 -c account_id=xxxxxx -c stack_name=slurmminimal -c SshKeyPair=key -c VpcId=vpc-0ff9de2afc42ab3 -c SubnetId=subnet-0456bccaac4a63914 -c ErrorSnsTopicArn=arn:aws:sns:us-east-1:098962443:ErrorSlurm -c SubmitterSecurityGroupIds=eyJzZ1NsdXJtIjogInNnLTA0MjgxZDc2ZjljNGEwZGNmIn0=

But when I minimal deploy with 

> ./install.sh --prompt --cdk-cmd create

CDK would bootstrap again and failed to get a value from App()

> ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists.
> Traceback (most recent call last):
> File "app.py", line 24, in <module>
> app = App()

I have configured aws secret id and key, and also region. The user and ec2 roles don't have any IAM permission.

_Originally posted by @lihnm in https://github.com/aws-samples/aws-eda-slurm-cluster/discussions/12#discussioncomment-2974253_

**Comment by lihnm** [comment]
**Solved**: 

I recommend anyone who has the same issue like me should use AWS Cloud9 IDE to bypass the **ERROR:root:No token file found**.

**Comment by cartalla** [comment]
Customer issue has been resolved.
Not sure, but think it was a networking issue with the instance that was being used.
